### ISSUE TITLE
Error flood with my historical data

### ISSUE THREAD

**Issue by mychaelo** [ESOUIMods/AdvancedMemberTooltip#1]
AMT causes the LibHistorie to break and flood DebugLogger with an error each and every frame. I discovered this when I noticed on a character with AMT activated I have half the framerate and twice the latency. The errors read as this:
```lua
user:/AddOns/LibHistoire/Codec.lua:302: operator .. is not supported for nil .. string
stack traceback:
user:/AddOns/LibHistoire/Codec.lua:302: in function 'DecodeData'
|caaaaaa<Locals> format = [table:1]{}, separator = ";", data = [table:2]{} </Locals>|r
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheEntry.lua:203: in function 'GuildHistoryCacheEntry:Deserialize'
|caaaaaa<Locals> self = [table:3]{}, idOffset = 1275321264, timeOffset = 1588363685, info = [table:4]{} </Locals>|r
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheEntry.lua:167: in function 'GuildHistoryCacheEntry:Initialize'
|caaaaaa<Locals> self = [table:3], cacheCategory = [table:5]{key = "EU Megaserver/335432/1", eventIndexLookupDirty = F, lastIndex = 1778, category = 1, guildId = 335432, progressDirty = T, waitForMore = 1778} </Locals>|r
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheEntry.lua:153: in function 'GuildHistoryCacheEntry:New'
|caaaaaa<Locals> self = [table:6]{}, object = [table:3] </Locals>|r
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:125: in function 'GuildHistoryCacheCategory:GetEvent'
|caaaaaa<Locals> self = [table:5], i = 8784 </Locals>|r
user:/AddOns/LibHistoire/guildHistoryCache/GuildHistoryCacheCategory.lua:152: in function 'EventIterator'
|caaaaaa<Locals> categoryCache = [table:5], index = 8784 </Locals>|r
user:/AddOns/LibAsync/LibAsync.lua:319: in function '(anonymous)'
(tail call): ?
[C]: in function 'pcall'
user:/AddOns/LibAsync/LibAsync.lua:37: in function 'DoCallback'
|caaaaaa<Locals> job = [table:7]{lastCallIndex = 2, name = "LibHistoire25", Error = "user:/AddOns/LibHistoire/Codec..."}, callstackIndex = 2 </Locals>|r
user:/AddOns/LibAsync/LibAsync.lua:67: in function 'DoJob'
|caaaaaa<Locals> job = [table:7], index = 2 </Locals>|r
user:/AddOns/LibAsync/LibAsync.lua:145: in function 'async.Scheduler'
|caaaaaa<Locals> name = "LibHistoire25", runTime = 6708.1112247, GetGameTimeSeconds = [C]:-1, start = 6708.1069335938, now = 6708.1112247, allOnlyOnce = F </Locals>|r
```
I can supply the `LibHistoire.lua` data file if needed

@Sharlikran

**Comment by Sharlikran** [comment]
I run 3 possibly 4 programs now off of LibHistorie. Some for personal use and development. I can't reproduce that error.

A Quote from the author
> no idea. the data in the error message doesn't make sense, so there has to be something else going on. according to the shown local values, it tries to get the event with index 8784 in the general category of the guild with id 335432, but for some reason that entry is nil, which is impossible. GuildHistoryCacheCategory.lua:125 should not be reached, since self.events[i] cannot be false in that case.
> without more information there is not much I can do. maybe ask him if he can send you his LibHistoire.lua and LibDebugLogger.lua from the saved vars?

I don't believe it is something in AMT, if I am wrong I am happy to address it. However, go ahead and provide the file and a link to the LibDebugLogger file please.

**Comment by Sharlikran** [comment]
I recycle the same code for LibHistorie that I use for MM, including my Refresh option so I am fairly confident of how well it works. Some people are starting to use LibHistorie and either copy my code or attempt to make their own. I can't guarantee that something else is happening because of other routines.

**Comment by mychaelo** [comment]
Here's the thing, that index does not exist. 8783 and then straight to 8785. I've been using LibHistoire with only two add-ons so far, MM3 for however long it's been released, and now AMT yesterday.

**Comment by Sharlikran** [comment]
Everytime I report something to the author he usually feels that shouldn't happen and requests information from me. So far I haven't been able to get any of that information. When it's you that I won't go into details about because it doesn't pertain to what you reported, he said if he had known about it earlier you would have found some way to address it.

When you have time can you provide the two things that I requested please.

**Comment by mychaelo** [comment]
@Sharlikran Here are the files along with a quickly hacked tool for finding the suspicious lines. I had to log out immediately after loading AMT so that the `LibDebugLogger.lua` doesn't cycle away any errors. It still managed to produce 3300 errors in those few seconds.
[LH_investigation.zip](https://github.com/ESOUIMods/AdvancedMemberTooltip/files/6200637/LH_investigation.zip)

**Comment by sirinsidiator** [comment]
Hi @mychaelo. I've been looking into this issue just now and it looks like there is a hole in your data, as it jumps from Dec 12th to Dec 22nd. I'm now wondering if this hole in the data has appeared on its own, or if you have modified the file? Depending on the answer I'll have to make some adjustments to the library.

Either way, the best course of action for now is to reorganize the data in the file so the missing index disappears. The easiest way to achieve this is by running the following chat command ingame:
`/script LibHistoire_GuildHistory["EU Megaserver/335432/1"][8784] = ""; table.remove(LibHistoire_GuildHistory["EU Megaserver/335432/1"], 8784); ReloadUI()`

**Comment by mychaelo** [comment]
@sirinsidiator The hole should actually be at around 29dec to 6th of jan, as I was far away from my PC till the middle of January (for obvious reasons). My tool found a few other holes as evidenced in `output.txt`, should I adjust your command to close them as well?

**Comment by sirinsidiator** [comment]
Ok. I just did a quick calculation by hand, so it's entirely possible that I'm off by a few days.
As for the other holes, as long as they don't cause any errors I'd just leave them. I'll add some code to the next version of the lib that will automatically fix the indices and add some safeguards so it won't fail again.

**Comment by mychaelo** [comment]
@sirinsidiator In libdebuglogger file I've spotted at least 3 different index values causing havoc, so I might nuke all 6 of the holes just to be sure.

**Comment by mychaelo** [comment]
6 UI reloads later I managed to plug all the holes and stop LibHistoire from misbehaving. Closing this issue as it's irrelevant to AMT.
